# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{proxymachine}
  s.version = "1.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Preston-Werner"]
  s.date = %q{2011-02-01}
  s.default_executable = %q{proxymachine}
  s.email = %q{tom@mojombo.com}
  s.executables = ["proxymachine"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "History.txt",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION.yml",
    "bin/proxymachine",
    "examples/git.rb",
    "examples/long.rb",
    "examples/transparent.rb",
    "lib/proxymachine.rb",
    "lib/proxymachine/client_connection.rb",
    "lib/proxymachine/server_connection.rb",
    "proxymachine.gemspec",
    "test/configs/simple.rb",
    "test/proxymachine_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/mojombo/proxymachine}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{ProxyMachine is a simple content aware (layer 7) TCP routing proxy.}
  s.test_files = [
    "examples/git.rb",
    "examples/long.rb",
    "examples/transparent.rb",
    "test/configs/simple.rb",
    "test/proxymachine_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<proxymachine>, [">= 0"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.10"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.10"])
    else
      s.add_dependency(%q<proxymachine>, [">= 0"])
      s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
    end
  else
    s.add_dependency(%q<proxymachine>, [">= 0"])
    s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
  end
end

